travis:
  secure:
    BINSTAR_TOKEN: cdRuK2Ktf0G9k5scf9S3823xt2Aq1Ic1AVV5ApkJ4TGSxy+AjwZBw+Heevm+DlLdFZqDH48lXTHYTKrv5byVNOENgk0L/emO46VhDrVzIs804Ck91KkFNqjjo9n9/QysX0PRvFp36LG4Uec1YhVjtcuFXEAOMCVQ0zAlcRtXOzaS3V1lO9u9evYs8fzPAtDSQGNtHKr4qsveSuQOGXEPi+XCpAM7M9Vo6OTBJn9o5N6UxB9SCRIqafCz5NEucE+S0qRVbpRj4kWkACQO3YnlHbnUJtSRxPWDJZuPmqH8HA8TwLZzXUC8v+/vlpuZ5U84O1C8/9w0dG4Ev0K+1BONuR8ieOLvHlTqr+s6jumKqX5m1I0kgHD8Rh46KJmewRhc0hWAG1uIouIelE2TakTEc4CpYwguQdoRwt2XXI249JA5D4sJmm5CIhORlerpsaLu6MfSThw01vRCsYsHCp+2Q/K/9j1F3JcOzzXZ6J0g9EXZM+HFnP205CuC2/TVWXIU/+INR06L0rFO2EsPaXcEG3j0c6koVPJkFRFGLvM7tDcH2asqHGEqG4ZnCwOrP4e94MgCsZB16KZ9+n/GPSL30/dHRKYGQYZa8eQmbjNpPyCjGX4x/8OXDeuycVVNjXtOwtqfbtGRkde73DVE3+1OCnk3eZYXTtVPLrUByITy9wY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
